Check for docker daemon

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -40,9 +40,20 @@ determine_distro() {
 }
 
 determine_sudo() {
+    if [[ "$__distro" =~ "debian" || "$__distro" = "ubuntu" ]]; then
+        systemctl status docker >/dev/null
+        result=$?
+        if [ ! "${result}" -eq 0 ]; then
+            echo "The Docker daemon is not running. Please check Docker installation."
+            echo "\"sudo systemctl status docker\" and \"sudo journalctl -fu docker\" will be helpful."
+            echo "Aborting."
+            exit 1
+        fi
+    fi
+
     __maybe_sudo=""
     if ! docker images >/dev/null 2>&1; then
-        echo "Will use sudo to access docker"
+        echo "Will use sudo to access Docker"
         __maybe_sudo="sudo"
     fi
 }
@@ -681,17 +692,17 @@ command="$1"
 shift
 
 determine_distro
-determine_sudo
 handle_root
+prep_prometheus
 
 if [ "$command" = "install" ]; then
     $command "$@"
     exit "$?"
 fi
 
+determine_sudo
 determine_docker
 determine_compose
-prep_prometheus
 
 if [ "$command" = "install" ]; then
     $command "$@"
