Update ethd

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -50,10 +50,12 @@ determine_docker() {
 }
 
 determine_compose() {
-# This is mainly for Debian and docker-ce, where docker-compose does not exist
-  if ! type -P docker-compose >/dev/null 2>&1; then
+# Check for Compose V2 (docker compose) vs Compose V1 (docker-compose)
+  if docker compose version >/dev/null 2>&1; then
     __compose_exe="docker compose"
+    __old_compose=0
   else
+    __old_compose=1
     __compose_version=$($__maybe_sudo docker-compose --version | sed -n -e "s/.*version [v]\?\([0-9.-]*\).*/\1/p")
     __compose_version_major=$(echo "$__compose_version" | cut -f1 -d.)
     __compose_version_minor=$(echo "$__compose_version" | cut -f2 -d.)
@@ -133,16 +135,14 @@ check_for_snap() {
     if [[ "$__distro" = "ubuntu" && -n "$(which snap)" ]] && snap list 2>/dev/null | grep -qw 'docker'; then
         echo
         echo "WARNING! Snap docker package detected. This WILL result in issues."
-        echo "Removing the package will delete volumes and require a resync,"
-        echo "as well as re-import of all validator keys."
+        echo "Removing the package will delete volumes and require a resync."
         echo
         echo "Doing so is still highly recommended however."
         echo
         echo "The exact steps depend a little on whether there already is"
         echo "an apt version of docker installed as well, but in a nutshell"
         echo '"./ethd stop" followed by "sudo snap remove --purge docker"'
-        echo "and then a reboot, and as needed install docker.io or docker-ce with apt,"
-        echo "re-import keys and restart eth-docker."
+        echo "and then a reboot, and as needed install docker.io or docker-ce with apt."
         echo
         echo "Do join us on EthStaker Discord to work through this issue."
         echo
@@ -153,6 +153,7 @@ check_for_snap() {
 
 install() {
     check_for_snap
+    set -e
     while true; do
         read -rp "This will attempt to install docker and make your user part of the docker group. Do you wish to continue? (no/yes) " yn
         case $yn in
@@ -166,7 +167,7 @@ install() {
             echo "This script cannot install docker on Ubuntu ${__major_version}. Consider upgrading to 22.04 or 20.04"
         fi
         if [ -z "$(which docker)" ]; then
-            ${__auto_sudo} apt-get update && ${__auto_sudo} apt-get install -y ca-certificates curl gnupg lsb-release whiptail bc
+            ${__auto_sudo} apt-get update && ${__auto_sudo} apt-get install -y ca-certificates curl gnupg lsb-release whiptail bc chrony
             ${__auto_sudo} mkdir -p /etc/apt/keyrings
             ${__auto_sudo} curl -fsSL https://download.docker.com/linux/ubuntu/gpg | ${__auto_sudo} gpg --dearmor -o /etc/apt/keyrings/docker.gpg
             ${__auto_sudo} echo \
@@ -189,7 +190,12 @@ install() {
     elif [[ "$__distro" =~ "debian" ]]; then
         if [ -z "$(which docker)" ]; then
             ${__auto_sudo} apt-get update
-            ${__auto_sudo} apt-get -y install ca-certificates curl gnupg lsb-release whiptail bc
+            ${__auto_sudo} apt-get -y install ca-certificates curl gnupg lsb-release whiptail bc chrony
+            __major_version=$(lsb_release -r | cut -f2)
+            if [ "${__major_version}" -lt 10 ]; then
+                echo "This script cannot install docker on Debian ${__major_version}. Consider upgrading to 11 or 12."
+                exit 0
+            fi
             ${__auto_sudo} mkdir -p /etc/apt/keyrings
             ${__auto_sudo} curl -fsSL https://download.docker.com/linux/debian/gpg | ${__auto_sudo} gpg --dearmor -o /etc/apt/keyrings/docker.gpg
             ${__auto_sudo} echo \
@@ -201,10 +207,58 @@ install() {
         else
             echo "Docker is already installed"
         fi
+        __groups=$(${__as_owner} groups)
+        if [[ ! "$__groups" =~ "docker" ]]; then
+            echo "Making your user part of the docker group"
+            ${__auto_sudo} usermod -aG docker "${OWNER}"
+            echo "Please run newgrp docker or log out and back in"
+        else
+            echo "Your user is already part of the docker group"
+        fi
     else
         echo "This script does not know how to install docker on $__distro"
     fi
+    set +e
     return 0
+}
+
+# Warn user if space is low, so they can prune
+check_disk_space() {
+    __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
+    __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
+
+    re='^[0-9]+$'
+    if ! [[ "${__free_space}" =~ $re ]] ; then
+        echo "Unable to determine free disk space. This is likely a bug."
+        echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
+        return
+    fi
+
+    var="COMPOSE_FILE"
+    value=$(sed -n -e "s/^${var}=\(.*\)/\1/p" ".env" || true)
+
+# Literal match intended
+# shellcheck disable=SC2076
+    if [[ "${value}" =~ "bor.yml" ]] && [[ "${__free_space}" -lt 104857600 ]]; then
+        echo ""
+        echo "You are running bor and have less than 100 GiB of free disk space."
+        echo "If Avail reads 40 GiB or more, prune with ./ethd prune-bor:"
+        echo ""
+        df -h "${__docker_dir}"
+        echo ""
+        echo "If it's less than 40 GiB, you may need to resync Bor from scratch."
+        echo ""
+    elif [[ "${__free_space}" -lt 52428800 ]]; then
+        echo ""
+        echo "You have less than 50 GiB of free disk space:"
+        echo ""
+        df -h "${__docker_dir}"
+        echo ""
+        echo "Pruning does not appear an option for your client mix."
+        echo "A resync may help."
+        echo "If total space is less than 1.5 TiB, consider cloning to a larger drive."
+        echo ""
+    fi
 }
 
 # Arguments are passed, but shellcheck doesn't recognize that
@@ -215,13 +269,33 @@ update() {
     else
         __dirty=0
     fi
+
+    __free_space=$(df -P "$(pwd)" | awk '/[0-9]%/{print $(NF-2)}')
+
+    re='^[0-9]+$'
+    if ! [[ "${__free_space}" =~ $re ]] ; then
+        echo "Unable to determine free disk space. This is likely a bug."
+        echo "df reports $(df -P "$(pwd)") and __free_space is ${__free_space}"
+    elif [ "$(df -P "$(pwd)" | awk '/[0-9]%/{print $(NF-2)}')" -lt 1024 ]; then
+        echo "You have less than 1 MiB of space left on $(pwd)."
+        echo "Aborting, as an update is not safe."
+        exit 1
+    fi
+
+    __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
+    __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
+
+    re='^[0-9]+$'
+    if ! [[ "${__free_space}" =~ $re ]] ; then
+        echo "Unable to determine free disk space. This is likely a bug."
+        echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
+    elif [ "${__free_space}" -lt 1048576 ]; then
+        echo "You have less than 1 GiB of space left on ${__docker_dir}."
+        echo "Aborting, as an update is not safe."
+        exit 1
+    fi
+
     if [ -z "${ETHDSECUNDO-}" ]; then
-        if ${__as_owner} git branch | grep -q master; then
-            ${__as_owner} git branch -m master main
-            ${__as_owner} git fetch origin
-            ${__as_owner} git branch -u origin/main main
-            ${__as_owner} git remote set-head origin -a
-        fi
         # Do not track changes to ext-network.yml
         ${__as_owner} git update-index --assume-unchanged ext-network.yml
         ${__as_owner} git config pull.rebase false
@@ -234,31 +308,28 @@ update() {
 
     envmigrate
 
-    cmd build --pull
-    cmd --profile tools build --pull
-    exec 3>&1
-    exec 4>&2
-    exec 1> /dev/null
-    exec 2> /dev/null
-    docompose pull || true
-    exec 1>&3
-    exec 2>&4
-    echo
-    echo "Your ${ENV_FILE} configuration settings have been migrated to a fresh copy. You can \
-find the original contents in ${ENV_FILE}.bak."
+    dodocker system prune --force
+    if [ ${__old_compose} -eq 1 ]; then
+      docompose --profile tools pull --ignore-pull-failures
+    else
+      docompose --profile tools pull --ignore-buildable
+    fi
+    docompose --profile tools build --pull
 
-    echo
-    cmp -s "${ENV_FILE}" "${ENV_FILE}".bak
-    if [ $? -ne 0 ]; then
+    if ! cmp -s "${ENV_FILE}" "${ENV_FILE}".source; then
+        cp "${ENV_FILE}".source "${ENV_FILE}".bak
+        rm "${ENV_FILE}".source
+        echo "Your ${ENV_FILE} configuration settings have been migrated to a fresh copy. You can \
+find the original contents in ${ENV_FILE}.bak."
+        echo
         echo "List of changes made to ${ENV_FILE} during migration - current on left, original on right:"
         echo
         diff -y --suppress-common-lines "${ENV_FILE}" "${ENV_FILE}".bak
     else
-        echo "No changes made to ${ENV_FILE} during migration"
+        echo "No changes made to ${ENV_FILE} during update"
+        rm "${ENV_FILE}".source
     fi
-    echo
-    echo "Your ${ENV_FILE} configuration settings have been migrated to a fresh copy. You can \
-find the original contents in ${ENV_FILE}.bak."
+
     echo
     echo "An ./ethd up command will start using the new images and configuration."
     if [[ "$__distro" = "ubuntu" ]]; then
@@ -271,29 +342,12 @@ find the original contents in ${ENV_FILE}.bak."
     fi
 
     unset ETHDSECUNDO
-    if [[ "${ETHDSWITCHED-}" -eq 1 ]]; then
-        unset ETHDSWITCHED
-        echo
-        echo "You were migrated to the $(${__as_owner} git name-rev --name-only HEAD) branch of eth-docker"
-        echo
-    fi
-    # If this is called by an older version of ethd, envmigrate
-    # is in its own bash instance: Need to kill the ethd parent
-# shellcheck disable=SC2009
-    if ps $PPID | grep -q "ethd"; then
-        echo
-        echo "Updated from an older version of eth-docker. You'll see \"Terminated\","
-        echo "which keeps the update from running twice. This is normal and will"
-        echo "only happen this once."
-        echo
-        kill $PPID
-    fi
     check_for_snap
     if [ "${__dirty}" -eq 1 ]; then
         echo
         echo "WARNING"
         echo
-        echo "You have uncommitted local changes to eth-docker, which keeps updates from coming in."
+        echo "You have uncommitted local changes to polygon-docker, which keeps updates from coming in."
         echo "Please undo these changes or \"git commit\" them."
         echo "These are the files with local changes:"
         echo
@@ -317,15 +371,12 @@ envmigrate() {
     NEW_VARS=( )
 
     if [ "${EUID}" -eq 0 ]; then
-      sudo -u "${OWNER}" cp "${ENV_FILE}" "${ENV_FILE}".bak
+      sudo -u "${OWNER}" cp "${ENV_FILE}" "${ENV_FILE}".source
       sudo -u "${OWNER}" cp default.env "${ENV_FILE}"
-      sudo -u "${OWNER}" cp "${ENV_FILE}".bak .env.source
     else
-      cp "${ENV_FILE}" "${ENV_FILE}".bak
+      cp "${ENV_FILE}" "${ENV_FILE}".source
       cp default.env "${ENV_FILE}"
-      cp "${ENV_FILE}".bak .env.source
     fi
-    __pre_merge=0
     # Migrate over user settings
     for var in "${ALL_VARS[@]}"; do
         value=$(sed -n -e "s/^${var}=\(.*\)/\1/p" ".env.source" || true)
@@ -341,7 +392,6 @@ envmigrate() {
             sed -i'.original' -e "s~^\(${NEW_VARS[index]}\s*=\s*\).*$~\1${value}~" "${ENV_FILE}"
         fi
     done
-    rm .env.source
     rm .env.original
 }
 
@@ -536,9 +586,8 @@ printhelp() {
     echo "subcommands:"
     echo "  install"
     echo "     attempts to install docker and docker-compose for you"
-    echo "  update [--keep-targets] "
-    echo "     updates all client versions and eth-docker itself"
-    echo "     --keep-targets will keep your custom build targets in .env"
+    echo "  update"
+    echo "     updates all client versions and polygon-docker itself"
     echo "  up (or start)"
     echo "     starts the Polygon node, or restarts containers that had their image or"
     echo "     configuration changed"
@@ -584,7 +633,7 @@ else
 fi
 
 if [ "${OWNER}" == "root" ]; then
-    echo "Please install eth-docker as a non-root user."
+    echo "Please install polygon-docker as a non-root user."
     exit 1
 fi
 
@@ -606,11 +655,6 @@ if [ "$command" = "install" ]; then
     exit "$?"
 fi
 
-if ! type -P whiptail >/dev/null 2>&1; then
-    echo "Please install the package whiptail or newt before running this script"
-    exit 1
-fi
-
 if ! dodocker images >/dev/null 2>&1; then
     echo "Please ensure you can call $__docker_exe before running this script."
     exit 1
@@ -622,3 +666,21 @@ if ! docompose --help >/dev/null 2>&1; then
 fi
 
 $command "$@"
+
+__result=$?
+if [ "$__result" -eq 127 ]; then
+    printhelp
+fi
+
+check_disk_space
+
+var="COMPOSEV1_NAG"
+value=$(sed -n -e "s/^${var}=\(.*\)/\1/p" ".env" || true)
+
+if [ "${value}" = true ] && [ "${__old_compose}" -eq 1 ]; then
+  echo
+  echo "You are using docker-compose ${__compose_version}, which is unsupported by Docker, Inc. from June 2023 on."
+  echo "A switch to docker-ce is recommended. It is *not* mandatory. This is unfortunately a manual step that polygon-docker cannot do for you."
+  echo "Please see https://eth-docker.net/Usage/Prerequisites#switching-from-dockerio-to-docker-ce for instructions."
+  echo "You can turn this message off by adjusting COMPOSEV1_NAG in .env"
+fi
